replicaCount: 2

image:
  tag: production-core-v2.0.1

deployment:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 120

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  maxUnavailable: 1
