apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "core-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "core-service.name" . }}
    spec:
      containers:
        - name: core-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
