resources:
  - ../../base

patches:
  - path: auth-patch.yml
  - path: core-patch.yml
  - path: gateway-patch.yml

images:
  - name: danyafi/auth-service
    newTag: latest
  - name: danyafi/core-service
    newTag: latest
  - name: danyafi/api-gateway
    newTag: latest
